// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mock_service_test.go -package=api
//

// Package api is a generated GoMock package.
package api

import (
	context "context"
	domain "goph-profile/internal/domain"
	io "io"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAvatarService is a mock of AvatarService interface.
type MockAvatarService struct {
	ctrl     *gomock.Controller
	recorder *MockAvatarServiceMockRecorder
	isgomock struct{}
}

// MockAvatarServiceMockRecorder is the mock recorder for MockAvatarService.
type MockAvatarServiceMockRecorder struct {
	mock *MockAvatarService
}

// NewMockAvatarService creates a new mock instance.
func NewMockAvatarService(ctrl *gomock.Controller) *MockAvatarService {
	mock := &MockAvatarService{ctrl: ctrl}
	mock.recorder = &MockAvatarServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAvatarService) EXPECT() *MockAvatarServiceMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockAvatarService) Delete(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockAvatarServiceMockRecorder) Delete(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAvatarService)(nil).Delete), arg0, arg1, arg2)
}

// Get mocks base method.
func (m *MockAvatarService) Get(arg0 context.Context, arg1, arg2 string) (*domain.Avatar, io.ReadCloser, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1, arg2)
	ret0, _ := ret[0].(*domain.Avatar)
	ret1, _ := ret[1].(io.ReadCloser)
	ret2, _ := ret[2].(string)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// Get indicates an expected call of Get.
func (mr *MockAvatarServiceMockRecorder) Get(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockAvatarService)(nil).Get), arg0, arg1, arg2)
}

// List mocks base method.
func (m *MockAvatarService) List(arg0 context.Context, arg1 string) ([]domain.Avatar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1)
	ret0, _ := ret[0].([]domain.Avatar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockAvatarServiceMockRecorder) List(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockAvatarService)(nil).List), arg0, arg1)
}

// Metadata mocks base method.
func (m *MockAvatarService) Metadata(arg0 context.Context, arg1 string) (*domain.Avatar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Metadata", arg0, arg1)
	ret0, _ := ret[0].(*domain.Avatar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Metadata indicates an expected call of Metadata.
func (mr *MockAvatarServiceMockRecorder) Metadata(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Metadata", reflect.TypeOf((*MockAvatarService)(nil).Metadata), arg0, arg1)
}

// Upload mocks base method.
func (m *MockAvatarService) Upload(arg0 context.Context, arg1, arg2 string, arg3 io.Reader, arg4 int64) (*domain.Avatar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upload", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(*domain.Avatar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upload indicates an expected call of Upload.
func (mr *MockAvatarServiceMockRecorder) Upload(arg0, arg1, arg2, arg3, arg4 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upload", reflect.TypeOf((*MockAvatarService)(nil).Upload), arg0, arg1, arg2, arg3, arg4)
}
