apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "goph-profile.fullname" . }}
  labels: {{- include "goph-profile.labels" . | nindent 4 }}
data:
  log-level: {{ .Values.config.logLevel | quote }}
  s3-endpoint: {{ .Values.config.s3Endpoint | quote }}
  s3-bucket: {{ .Values.config.s3Bucket | quote }}
  s3-use-ssl: {{ .Values.config.s3UseSSL | quote }}
  otlp-endpoint: {{ .Values.config.otlpEndpoint | quote }}
