{{- if .Values.migrations.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "goph-profile.fullname" . }}-migrations
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "-10"
    helm.sh/hook-delete-policy: before-hook-creation
data:
  001_init.sql: |
{{ .Files.Get "files/001_init.sql" | indent 4 }}
{{- end }}
