{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "goph-profile.fullname" . }}
  labels: {{- include "goph-profile.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-url: {{ required "secrets.databaseURL is required" .Values.secrets.databaseURL | quote }}
  s3-access-key: {{ required "secrets.s3AccessKey is required" .Values.secrets.s3AccessKey | quote }}
  s3-secret-key: {{ required "secrets.s3SecretKey is required" .Values.secrets.s3SecretKey | quote }}
  rabbitmq-url: {{ required "secrets.rabbitmqURL is required" .Values.secrets.rabbitmqURL | quote }}
{{- end }}
