image:
  tag: stable
  pullPolicy: IfNotPresent
migrations:
  image:
    tag: stable
secrets:
  existingSecret: goph-profile-secrets
  databaseURL: ""
  s3AccessKey: ""
  s3SecretKey: ""
  rabbitmqURL: ""
server:
  replicaCount: 3
worker:
  replicaCount: 3
ingress:
  hosts:
    - host: avatars.example.com
      paths: [{path: /, pathType: Prefix}]
